version: '3.8'
services:
  postgres-db:
    build: sonar/postgres/.
    ports:
    - "5432:5432"
  sonarcube:
    build: sonar/.
    ports:
      - "9000:9000"
    depends_on:
      - postgres-db
  jenkins:
    build: jenkins/.
    ports:
      - "9080:8080"